server:
  port: 8080
spring:
  redis:  #redis配置
    host: 175.178.236.116
    port: 6379
    password: mdjfbzyj515
  datasource: #mysql配置
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/app?characterEncoding=utf-8&useSSL=false
    username: root
    password: mdjfbzyj515